django_app/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from blog import views as blog_views
from mysite import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # blog/urls.py를 사용하지 않고 루트 urls.py를 사용할 경우
    # url(r'^$', blog_views.post_list, name='post_list'),

    # blog/urls.py의 내용을 사용할 경우
    url(r'', include('blog.urls', namespace='blog')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^video/', include('video.urls', namespace='video')),
    url(r'^sns/', include('sns.urls', namespace='sns')),
]

django_app/sns/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^facebook/friends_ranking/$', views.friends_ranking, name='friends_ranking'),
]

django_app/video/urls.py
from django.conf.urls import url
from video import views

urlpatterns = [
    url(r'^bookmark/list/$', views.bookmark_list, name='bookmark_list'),
    url(r'^bookmark/add/$', views.bookmark_add, name='bookmark_add'),
    url(r'^bookmark/(?P<pk>\d+)/$', views.bookmark_detail, name='bookmark_detail'),
    url(r'^search/$', views.search, name='search'),
]

django_app/video/models.py
from django.db import models


class Video(models.Model):
    kind = models.CharField(max_length=100)
    youtube_id = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    published_date = models.DateTimeField()
    thumbnail = models.URLField(blank=True)

    def __str__(self):
        return self.title

django_app/video/views/bookmark.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from video.models import Video
__all__ = [
    'bookmark_add',
    'bookmark_list',
    'bookmark_detail',
]


def bookmark_add(request):
    path = request.POST.get('path')
    try:
        kind = request.POST['kind']
        video_id = request.POST['video_id']
        title = request.POST['title']
        description = request.POST['description']
        published_date = request.POST['published_date']
        thumbnail_url = request.POST['thumbnail_url']

        video = Video.objects.create(
            kind=kind,
            youtube_id=video_id,
            title=title,
            description=description,
            published_date=published_date,
            thumbnail=thumbnail_url
        )
        msg = '%s 영상을 북마크에 등록했습니다' % (
            video.title
        )
    except Exception as e:
        msg = 'Exception! %s (%s)' % (e, e.args)

    messages.success(request, msg)
    if path:
        return redirect(path)
    else:
        return redirect('video:bookmark_list')


def bookmark_list(request):
    """
    추가한 Video인스턴스 목록을 보여주는 페이지
    """
    videos = Video.objects.all()
    context = {
        'videos': videos,
    }
    return render(request, 'video/bookmark_list.html', context)


def bookmark_detail(request, pk):
    """
    pk에 해당하는 Video 인스턴스를 리턴
    템플릿은 video/bookmark_detail.html사용
    extra
        get_object_or_404를 써봅니다
    """
    video = Video.objects.get(pk=pk)
    context = {
        'video': video
    }
    return render(request, 'video/bookmark_detail.html', context)

django_app/video/views/search.py
from django.shortcuts import render
from video.apis.youtube import youtube_search

# 이 모듈을 import시킬 때
# from views.search import *
# 을 입력해도 search함수만 import하게된다
__all__ = ['search']


def search(request):
    # Template : 'video/search.html'
    # URL : 'video/search/'
    # view : search
    # Static, Templates 디렉토리 설정
    """
    1. STATICFILES_DIRS 설정
    2. templates폴더 생성 후 TEMPLATE의 DIRS안에 설정
    3. video/search.html파일 생성
    4. search.html내부 내용
        input
        ul > li (img, p*3)
    5. urls.py에 view연결
    6. view에서 video/search.html파일 render
    """
    # GET paramter에서 keyword값을 가져옵니다

    # 빈 dict요소 생성
    context = {}

    # request.GET의 parameter에서 keyword, page_token값을 가져옴
    keyword = request.GET.get('keyword')
    page_token = request.GET.get('page_token')

    # 만약 keyword값이 존재할 경우 (request.GET의 keyword키로 값이 넘어올 경우)
    # context dict에 keyword, response에 값 할당해줌
    if keyword:
        response = youtube_search(keyword, page_token)
        context['keyword'] = keyword
        context['response'] = response
    # 검색을 안 할 경우 빈 dict요소만 가지고 렌더링
    return render(request, 'video/search.html', context)

django_app/templates/video/bookmark_detail.html
{% extends 'common/base.html' %}
<!-- video인스턴스를 받아 플레이어 출력 -->

{% block content %}

<div>{{ video.youtube_id }}</div>

<iframe
	width="560"
	height="315"
	src="https://www.youtube.com/embed/{{ video.youtube_id }}"
	frameborder="0"
	allowfullscreen>
</iframe>
{% endblock %}

django_app/templates/video/bookmark_list.html
{% extends 'common/base.html' %}

{% block content %}

<!-- 검색화면으로 가기 버튼 구현 -->
<a href="{% url 'video:search' %}" class="btn btn-primary">Search videos...</a>

<ul>
	{% for video in videos %}
	<li>
		<a href="{% url 'video:bookmark_detail' pk=video.pk %}">
			<img src="{{ video.thumbnail }}" alt="">
		</a>
		<p>Title : {{ video.title }}</p>
		<p>Description : {{ video.description }}</p>
		<p>Published : {{ video.published_date|date:"Y.m.d" }}</p>
	</li>
	{% endfor %}
</ul>


{% endblock %}

django_app/templates/video/search.html
{% extends 'common/base.html' %}
{% load app_filters %}
{% load humanize %}

{% block content %}
	<h5>"{{ keyword }}"로 검색 (총 {{ response.pageInfo.totalResults|intcomma }}건의 검색결과)</h5>
	<form action="">
		<input type="text" name="keyword" placeholder="{{ keyword }}">
		<button type="submit">검색</button>
	</form>

	<ul>
		{% for item in response.items %}
		<li>
			<img src="{{ item.snippet.thumbnails.medium.url }}" alt="">
			<p>{{ item.snippet.title }}</p>
			<p>{{ item.snippet.description }}</p>
			<p>{{ item.snippet.publishedAt|string_to_date|date:"Y.m.d h:i" }}</p>
			<p>View count : {{ item.statistics.viewCount|intcomma }}</p>
			<p>Like count : {{ item.statistics.likeCount|intcomma }}</p>
			<p>Comment count : {{ item.statistics.commentCount|intcomma }}</p>
			<div>
				{% for tag in item.snippet.tags %}
				<span class="label label-default">{{ tag }}</span>
				{% endfor %}
			</div>

			<!--
				form에서 video:bookmark_add URL에 POST요청
				요청하는 name은 view에서 참조
				각 input에 value에 값을 지정
			-->
			{% if item.is_exist %}
			<button>Already added</button>
			{% else %}
			<form action="{% url 'video:bookmark_add' %}" method="POST">{% csrf_token %}
				<input type="hidden" name="kind" value="{{ item.kind }}">
				<input type="hidden" name="video_id" value="{{ item.id }}">
				<input type="hidden" name="title" value="{{ item.snippet.title }}">
				<input type="hidden" name="description" value="{{ item.snippet.description }}">
				<input type="hidden" name="published_date" value="{{ item.snippet.publishedAt }}">
				<input type="hidden" name="thumbnail_url" value="{{ item.snippet.thumbnails.high.url }}">
				<input type="hidden" name="path" value="{{ request.get_full_path }}">
				<button type="submit">Add bookmark</button>
			</form>
			{% endif %}
		</li>
		{% endfor %}
		<!--
			response내부에 nextPageToken, prevPageToken이 있는경우를 판단해서
			이전페이지/다음페이지 버튼을 만들어보세요

			URL에 Get parameter설정법 공부하세요
		-->
		{% if response.prevPageToken %}
		<a href="{% url 'video:search' %}?keyword={{ keyword }}&page_token={{ response.prevPageToken }}">이전페이지</a>
		{% endif %}

		<!--
			첫 페이지로 가기 버튼 만들어보세요
				(첫 페이지에선 나오면 안 됩니다)
		-->
		{% if response.prevPageToken %}
		<a href="{% url 'video:search' %}?keyword={{ keyword }}">첫 페이지로 가기</a>
		{% endif %}


		{% if response.nextPageToken %}
		<a href="{% url 'video:search' %}?keyword={{ keyword }}&page_token={{ response.nextPageToken }}">다음페이지</a>
		{% endif %}
	</ul>
{% endblock %}