django_app/blog/urls.py
from django.conf.urls import url
from . import views

# {} <- 이거 아닙니다
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^comment/add/(?P<post_pk>[0-9]+)/$', views.comment_add, name='comment_add'),
]

django_app/member/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^login/facebook/$', views.login_facebook, name='login_facebook'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signup2/$', views.signup2, name='signup2'),
    url(r'^signup3/$', views.signup3, name='signup3'),
]

django_app/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from blog import views as blog_views
from mysite import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # blog/urls.py를 사용하지 않고 루트 urls.py를 사용할 경우
    # url(r'^$', blog_views.post_list, name='post_list'),

    # blog/urls.py의 내용을 사용할 경우
    url(r'', include('blog.urls', namespace='blog')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^video/', include('video.urls', namespace='video')),
    url(r'^sns/', include('sns.urls', namespace='sns')),
]

django_app/sns/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^facebook/friends_ranking/$', views.friends_ranking, name='friends_ranking'),
]

django_app/video/urls.py
from django.conf.urls import url
from video import views

urlpatterns = [
    url(r'^bookmark/list/$', views.bookmark_list, name='bookmark_list'),
    url(r'^bookmark/add/$', views.bookmark_add, name='bookmark_add'),
    url(r'^bookmark/(?P<pk>\d+)/$', views.bookmark_detail, name='bookmark_detail'),
    url(r'^search/$', views.search, name='search'),
]

django_app/templates/common/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>이한영의 홈페이지에 오신것을 환영합니다</title>

  <!-- https://tutorial.djangogirls.org/ko/css/ -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/common.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/blog.min.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <!-- Facebook SDK -->
  <div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/ko_KR/sdk.js#xfbml=1&version=v2.8";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <!-- a.navbar-brand [tab] -->
        <a href="{% url 'blog:post_list' %}" class="navbar-brand">lhy's Blog</a>
      </div>

      <!-- div.collapse.navbar-collapse#main-navbar [tab] -->
      <div class="collapse navbar-collapse" id="main-navbar">
        <!-- ul.nav.navbar-nav.navbar-right [tab] -->
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li>
            <p class="navbar-text">{{ user.email }}</p>
          </li>
          <li>
            <a href="{% url 'blog:post_list' %}">Blog</a>
          </li>
          <li>
            <a href="{% url 'video:bookmark_list' %}">Video</a>
          </li>
          <li>
            <a href="{% url 'blog:post_new' %}">
              <span class="glyphicon glyphicon-plus"></span> New post
            </a>
          </li>
          <li>
            <a href="{% url 'member:logout' %}">Logout</a>
          </li>
          {% else %}
          <li>
            <a href="{% url 'member:login' %}?next={{ request.path }}">Login</a>
          </li>
          <li>
            <a href="{% url 'member:signup3' %}?next={{ request.path }}">Signup</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    {% if messages %}
    <div>
      {% for message in messages %}
        <div class="alert
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}alert-danger
          {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}alert-info
          {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}alert-success
          {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}alert-warning
          {% elif message.level == DEFAULT_MESSAGE_LEVELS.DEBUG %}alert-danger
          {% endif %}" role="alert">
          <span>{{ message }}</span>
        </div>
      {% endfor %}
    </div>
    {% endif %}

    <div>
      {% block content %}
      {% endblock %}
    </div>
  </div>
</body>
</html>

django_app/templates/common/error.html
{% extends 'base.html' %}

{% block content %}
<p>{{ error_message }}</p>
{% endblock %}